// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package rpc

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// StudentRpcClient is the client API for StudentRpc service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type StudentRpcClient interface {
	AddStudent(ctx context.Context, in *StudentAddReq, opts ...grpc.CallOption) (*StudentAddRes, error)
}

type studentRpcClient struct {
	cc grpc.ClientConnInterface
}

func NewStudentRpcClient(cc grpc.ClientConnInterface) StudentRpcClient {
	return &studentRpcClient{cc}
}

func (c *studentRpcClient) AddStudent(ctx context.Context, in *StudentAddReq, opts ...grpc.CallOption) (*StudentAddRes, error) {
	out := new(StudentAddRes)
	err := c.cc.Invoke(ctx, "/rpc.studentRpc/AddStudent", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// StudentRpcServer is the server API for StudentRpc service.
// All implementations must embed UnimplementedStudentRpcServer
// for forward compatibility
type StudentRpcServer interface {
	AddStudent(context.Context, *StudentAddReq) (*StudentAddRes, error)
	mustEmbedUnimplementedStudentRpcServer()
}

// UnimplementedStudentRpcServer must be embedded to have forward compatible implementations.
type UnimplementedStudentRpcServer struct {
}

func (UnimplementedStudentRpcServer) AddStudent(context.Context, *StudentAddReq) (*StudentAddRes, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AddStudent not implemented")
}
func (UnimplementedStudentRpcServer) mustEmbedUnimplementedStudentRpcServer() {}

// UnsafeStudentRpcServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to StudentRpcServer will
// result in compilation errors.
type UnsafeStudentRpcServer interface {
	mustEmbedUnimplementedStudentRpcServer()
}

func RegisterStudentRpcServer(s grpc.ServiceRegistrar, srv StudentRpcServer) {
	s.RegisterService(&StudentRpc_ServiceDesc, srv)
}

func _StudentRpc_AddStudent_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StudentAddReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StudentRpcServer).AddStudent(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/rpc.studentRpc/AddStudent",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StudentRpcServer).AddStudent(ctx, req.(*StudentAddReq))
	}
	return interceptor(ctx, in, info, handler)
}

// StudentRpc_ServiceDesc is the grpc.ServiceDesc for StudentRpc service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var StudentRpc_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "rpc.studentRpc",
	HandlerType: (*StudentRpcServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "AddStudent",
			Handler:    _StudentRpc_AddStudent_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "studentrpc.proto",
}
