// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.19.4
// source: studentrpc.proto

package rpc

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Student struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	SName     string `protobuf:"bytes,1,opt,name=sName,proto3" json:"sName,omitempty"`
	SEmail    string `protobuf:"bytes,2,opt,name=sEmail,proto3" json:"sEmail,omitempty"`
	SPassword string `protobuf:"bytes,3,opt,name=sPassword,proto3" json:"sPassword,omitempty"`
}

func (x *Student) Reset() {
	*x = Student{}
	if protoimpl.UnsafeEnabled {
		mi := &file_studentrpc_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Student) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Student) ProtoMessage() {}

func (x *Student) ProtoReflect() protoreflect.Message {
	mi := &file_studentrpc_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Student.ProtoReflect.Descriptor instead.
func (*Student) Descriptor() ([]byte, []int) {
	return file_studentrpc_proto_rawDescGZIP(), []int{0}
}

func (x *Student) GetSName() string {
	if x != nil {
		return x.SName
	}
	return ""
}

func (x *Student) GetSEmail() string {
	if x != nil {
		return x.SEmail
	}
	return ""
}

func (x *Student) GetSPassword() string {
	if x != nil {
		return x.SPassword
	}
	return ""
}

type StudentAddReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Student *Student `protobuf:"bytes,1,opt,name=student,proto3" json:"student,omitempty"`
}

func (x *StudentAddReq) Reset() {
	*x = StudentAddReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_studentrpc_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *StudentAddReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StudentAddReq) ProtoMessage() {}

func (x *StudentAddReq) ProtoReflect() protoreflect.Message {
	mi := &file_studentrpc_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StudentAddReq.ProtoReflect.Descriptor instead.
func (*StudentAddReq) Descriptor() ([]byte, []int) {
	return file_studentrpc_proto_rawDescGZIP(), []int{1}
}

func (x *StudentAddReq) GetStudent() *Student {
	if x != nil {
		return x.Student
	}
	return nil
}

type StudentAddRes struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Code int32 `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
}

func (x *StudentAddRes) Reset() {
	*x = StudentAddRes{}
	if protoimpl.UnsafeEnabled {
		mi := &file_studentrpc_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *StudentAddRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StudentAddRes) ProtoMessage() {}

func (x *StudentAddRes) ProtoReflect() protoreflect.Message {
	mi := &file_studentrpc_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StudentAddRes.ProtoReflect.Descriptor instead.
func (*StudentAddRes) Descriptor() ([]byte, []int) {
	return file_studentrpc_proto_rawDescGZIP(), []int{2}
}

func (x *StudentAddRes) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

var File_studentrpc_proto protoreflect.FileDescriptor

var file_studentrpc_proto_rawDesc = []byte{
	0x0a, 0x10, 0x73, 0x74, 0x75, 0x64, 0x65, 0x6e, 0x74, 0x72, 0x70, 0x63, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x12, 0x03, 0x72, 0x70, 0x63, 0x22, 0x55, 0x0a, 0x07, 0x53, 0x74, 0x75, 0x64, 0x65,
	0x6e, 0x74, 0x12, 0x14, 0x0a, 0x05, 0x73, 0x4e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x05, 0x73, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x45, 0x6d, 0x61,
	0x69, 0x6c, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x73, 0x45, 0x6d, 0x61, 0x69, 0x6c,
	0x12, 0x1c, 0x0a, 0x09, 0x73, 0x50, 0x61, 0x73, 0x73, 0x77, 0x6f, 0x72, 0x64, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x09, 0x73, 0x50, 0x61, 0x73, 0x73, 0x77, 0x6f, 0x72, 0x64, 0x22, 0x37,
	0x0a, 0x0d, 0x53, 0x74, 0x75, 0x64, 0x65, 0x6e, 0x74, 0x41, 0x64, 0x64, 0x52, 0x65, 0x71, 0x12,
	0x26, 0x0a, 0x07, 0x73, 0x74, 0x75, 0x64, 0x65, 0x6e, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x0c, 0x2e, 0x72, 0x70, 0x63, 0x2e, 0x53, 0x74, 0x75, 0x64, 0x65, 0x6e, 0x74, 0x52, 0x07,
	0x73, 0x74, 0x75, 0x64, 0x65, 0x6e, 0x74, 0x22, 0x23, 0x0a, 0x0d, 0x53, 0x74, 0x75, 0x64, 0x65,
	0x6e, 0x74, 0x41, 0x64, 0x64, 0x52, 0x65, 0x73, 0x12, 0x12, 0x0a, 0x04, 0x63, 0x6f, 0x64, 0x65,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x32, 0x42, 0x0a, 0x0a,
	0x73, 0x74, 0x75, 0x64, 0x65, 0x6e, 0x74, 0x52, 0x70, 0x63, 0x12, 0x34, 0x0a, 0x0a, 0x41, 0x64,
	0x64, 0x53, 0x74, 0x75, 0x64, 0x65, 0x6e, 0x74, 0x12, 0x12, 0x2e, 0x72, 0x70, 0x63, 0x2e, 0x53,
	0x74, 0x75, 0x64, 0x65, 0x6e, 0x74, 0x41, 0x64, 0x64, 0x52, 0x65, 0x71, 0x1a, 0x12, 0x2e, 0x72,
	0x70, 0x63, 0x2e, 0x53, 0x74, 0x75, 0x64, 0x65, 0x6e, 0x74, 0x41, 0x64, 0x64, 0x52, 0x65, 0x73,
	0x42, 0x07, 0x5a, 0x05, 0x2e, 0x2f, 0x72, 0x70, 0x63, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x33,
}

var (
	file_studentrpc_proto_rawDescOnce sync.Once
	file_studentrpc_proto_rawDescData = file_studentrpc_proto_rawDesc
)

func file_studentrpc_proto_rawDescGZIP() []byte {
	file_studentrpc_proto_rawDescOnce.Do(func() {
		file_studentrpc_proto_rawDescData = protoimpl.X.CompressGZIP(file_studentrpc_proto_rawDescData)
	})
	return file_studentrpc_proto_rawDescData
}

var file_studentrpc_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_studentrpc_proto_goTypes = []interface{}{
	(*Student)(nil),       // 0: rpc.Student
	(*StudentAddReq)(nil), // 1: rpc.StudentAddReq
	(*StudentAddRes)(nil), // 2: rpc.StudentAddRes
}
var file_studentrpc_proto_depIdxs = []int32{
	0, // 0: rpc.StudentAddReq.student:type_name -> rpc.Student
	1, // 1: rpc.studentRpc.AddStudent:input_type -> rpc.StudentAddReq
	2, // 2: rpc.studentRpc.AddStudent:output_type -> rpc.StudentAddRes
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_studentrpc_proto_init() }
func file_studentrpc_proto_init() {
	if File_studentrpc_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_studentrpc_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Student); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_studentrpc_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*StudentAddReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_studentrpc_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*StudentAddRes); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_studentrpc_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_studentrpc_proto_goTypes,
		DependencyIndexes: file_studentrpc_proto_depIdxs,
		MessageInfos:      file_studentrpc_proto_msgTypes,
	}.Build()
	File_studentrpc_proto = out.File
	file_studentrpc_proto_rawDesc = nil
	file_studentrpc_proto_goTypes = nil
	file_studentrpc_proto_depIdxs = nil
}
