// Code generated by goctl. DO NOT EDIT!
// Source: teacherRpc.proto

package server

import (
	"context"
	"onlineEudcation/Teacher/Rpc/Rpc"
	"onlineEudcation/Teacher/Rpc/internal/logic"
	"onlineEudcation/Teacher/Rpc/internal/svc"
)

type TeacherRpcServer struct {
	svcCtx *svc.ServiceContext
	Rpc.UnimplementedTeacherRpcServer
}

func NewTeacherRpcServer(svcCtx *svc.ServiceContext) *TeacherRpcServer {
	return &TeacherRpcServer{
		svcCtx: svcCtx,
	}
}
func (s *TeacherRpcServer) Register(ctx context.Context, in *Rpc.TeacherInfo) (*Rpc.Response, error) {
	l := logic.NewRegisterLogic(ctx, s.svcCtx)
	return l.Register(in)
}
func (s *TeacherRpcServer) Login(ctx context.Context, in *Rpc.TeacherLoginInfo) (*Rpc.LoginResponse, error) {
	l := logic.NewLoginLogic(ctx, s.svcCtx)
	return l.Login(in)
}
