// Code generated by goctl. DO NOT EDIT.
package handler

import (
	"net/http"

	"onlineEudcation/Admin/api/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPost,
				Path:    "/searchCourses",
				Handler: searchNeededCoursesHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/changeCourseStatus",
				Handler: changeCourseStatusHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/getCensorList",
				Handler: getCensorListHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/addCensor",
				Handler: addCensorHandler(serverCtx),
			},
		},
		rest.WithPrefix("/admin"),
	)
}
