// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package Rpc

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// TeacherRpcClient is the client API for TeacherRpc service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type TeacherRpcClient interface {
	Register(ctx context.Context, in *TeacherInfo, opts ...grpc.CallOption) (*Response, error)
	Login(ctx context.Context, in *TeacherLoginInfo, opts ...grpc.CallOption) (*LoginResponse, error)
}

type teacherRpcClient struct {
	cc grpc.ClientConnInterface
}

func NewTeacherRpcClient(cc grpc.ClientConnInterface) TeacherRpcClient {
	return &teacherRpcClient{cc}
}

func (c *teacherRpcClient) Register(ctx context.Context, in *TeacherInfo, opts ...grpc.CallOption) (*Response, error) {
	out := new(Response)
	err := c.cc.Invoke(ctx, "/Rpc.TeacherRpc/Register", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *teacherRpcClient) Login(ctx context.Context, in *TeacherLoginInfo, opts ...grpc.CallOption) (*LoginResponse, error) {
	out := new(LoginResponse)
	err := c.cc.Invoke(ctx, "/Rpc.TeacherRpc/Login", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// TeacherRpcServer is the server API for TeacherRpc service.
// All implementations must embed UnimplementedTeacherRpcServer
// for forward compatibility
type TeacherRpcServer interface {
	Register(context.Context, *TeacherInfo) (*Response, error)
	Login(context.Context, *TeacherLoginInfo) (*LoginResponse, error)
	mustEmbedUnimplementedTeacherRpcServer()
}

// UnimplementedTeacherRpcServer must be embedded to have forward compatible implementations.
type UnimplementedTeacherRpcServer struct {
}

func (UnimplementedTeacherRpcServer) Register(context.Context, *TeacherInfo) (*Response, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Register not implemented")
}
func (UnimplementedTeacherRpcServer) Login(context.Context, *TeacherLoginInfo) (*LoginResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Login not implemented")
}
func (UnimplementedTeacherRpcServer) mustEmbedUnimplementedTeacherRpcServer() {}

// UnsafeTeacherRpcServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to TeacherRpcServer will
// result in compilation errors.
type UnsafeTeacherRpcServer interface {
	mustEmbedUnimplementedTeacherRpcServer()
}

func RegisterTeacherRpcServer(s grpc.ServiceRegistrar, srv TeacherRpcServer) {
	s.RegisterService(&TeacherRpc_ServiceDesc, srv)
}

func _TeacherRpc_Register_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TeacherInfo)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TeacherRpcServer).Register(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/Rpc.TeacherRpc/Register",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TeacherRpcServer).Register(ctx, req.(*TeacherInfo))
	}
	return interceptor(ctx, in, info, handler)
}

func _TeacherRpc_Login_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TeacherLoginInfo)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TeacherRpcServer).Login(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/Rpc.TeacherRpc/Login",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TeacherRpcServer).Login(ctx, req.(*TeacherLoginInfo))
	}
	return interceptor(ctx, in, info, handler)
}

// TeacherRpc_ServiceDesc is the grpc.ServiceDesc for TeacherRpc service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var TeacherRpc_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "Rpc.TeacherRpc",
	HandlerType: (*TeacherRpcServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Register",
			Handler:    _TeacherRpc_Register_Handler,
		},
		{
			MethodName: "Login",
			Handler:    _TeacherRpc_Login_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "teacherRpc.proto",
}
