// Code generated by goctl. DO NOT EDIT.
package types

type CourseAddrequest struct {
	CourseName string `json:"courseName"`
	CourseTag  string `json:"courseTag"`
	TeacherId  int32  `json:"teacherId"`
	ImgUrl     string `json:"imgUrl"`
}

type Response struct {
	Code    uint16 `json:"code"`
	Message string `json:"message"`
	Res     bool   `json:"res"`
}

type CourseImg struct {
	File string `form:"file"`
}
