// Code generated by goctl. DO NOT EDIT.
package types

type SearchCourseByIdReq struct {
	TeacherId int32 `json:"teacherId"`
}

type SearchCourseByIdItem struct {
	CourseId          int32  `json:"courseId"`
	CourseName        string `json:"courseName"`
	CourseImg         string `json:"courseImg"`
	CourseType        string `json:"courseType"`
	CourseStatus      bool   `json:"courseStatus"`
	TeacherId         int32  `json:"teacherId"`
	CoursePlaySum     int32  `json:"coursePlaySum"`
	CourseVideoNumBer int32  `json:"courseVideoNumBer"`
}

type SearchCourseByIdRes struct {
	CourseList []SearchCourseByIdItem `json:"courseList"`
}

type CourseAddrequest struct {
	CourseName string `json:"courseName"`
	CourseTag  string `json:"courseTag"`
	TeacherId  int32  `json:"teacherId"`
	ImgUrl     string `json:"imgUrl"`
}

type Response struct {
	Code    uint16 `json:"code"`
	Message string `json:"message"`
	Res     bool   `json:"res"`
}

type CourseImg struct {
	File string `form:"file"`
}
