// Code generated by goctl. DO NOT EDIT.
package types

type Student struct {
	StudentId       int    `json:"sId"`
	StudentName     string `json:"sName"`
	StudentPassword string `json:"sPassword"`
	StudentEmail    string `json:"sEmail"`
}

type StudentLoginReq struct {
	StudentName     string `json:"sName"`
	StudentPassword string `json:"sPassword"`
}

type StudentLoginRes struct {
	Code    int    `json:"code"`
	IsFirst bool   `json:"isFirst"`
	Message string `json:"message"`
}

type StudentRegisterReq struct {
	Student
}

type StudentRegisterRes struct {
	Code    int    `json:"code"`
	Message string `json:"message"`
}
