// Code generated by goctl. DO NOT EDIT.
package types

type AddClassRequest struct {
	StudentId int `json:"studentId"`
	CourseId  int `json:"courseId"`
}

type Response struct {
	Code    int    `json:"code"`
	Message string `json:"message"`
}
