// Code generated by goctl. DO NOT EDIT.
package handler

import (
	"net/http"

	"onlineEudcation/Courses/Api/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPost,
				Path:    "/addCourse",
				Handler: addCourseHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/addCourseImg",
				Handler: addCourseImgHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/searchCourseById",
				Handler: searchCourseByIdHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/delCourse",
				Handler: delCourseHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/findCourseByCourseId",
				Handler: findCourseByCourseIdHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/updateCourseInfo",
				Handler: updateCourseInfoHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/getCourseList",
				Handler: getCourseListHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/getRecommendCourseList",
				Handler: getRecommendCourseListHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/courseHits",
				Handler: courseHitsHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/searchCourseByName",
				Handler: searchCourseByNameHandler(serverCtx),
			},
		},
		rest.WithPrefix("/course"),
	)
}
