// Code generated by goctl. DO NOT EDIT.
package handler

import (
	"net/http"

	"onlineEudcation/Teacher/Api/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPost,
				Path:    "/register",
				Handler: tRegisterHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/login",
				Handler: tLoginHandler(serverCtx),
			},
		},
		rest.WithPrefix("/teacher"),
	)
}
