// Code generated by goctl. DO NOT EDIT.
package types

type SearchCoursesReq struct {
	AdminID int `json:"admin_id"`
}

type Course struct {
	CourseId          int32  `json:"courseId"`
	CourseName        string `json:"courseName"`
	CourseImg         string `json:"courseImg"`
	CourseType        string `json:"courseType"`
	CourseStatus      bool   `json:"courseStatus"`
	CoursePlaySum     int32  `json:"coursePlaySum"`
	CourseVideoNumBer int32  `json:"courseVideoNumBer"`
	TeacherId         int    `json:"teacherId"`
}

type SearchCoursesRes struct {
	Courses []Course `json:"courses"`
}

type ChangeStatusReq struct {
	CourseId int32 `json:"courseId"`
}

type ChangeStatusRes struct {
	Code int `json:"code"`
}

type GetReq struct {
	TeacherId int `json:"teacherId"`
}

type CensorItem struct {
	ID           int    `json:"id"`
	CourseId     int    `json:"courseId"`
	TeacherId    int    `json:"teacherId"`
	CensorStatus bool   `json:"censorStatus"`
	Message      string `json:"message"`
}

type GetRes struct {
	CensorList []CensorItem `json:"censorList"`
}

type AddCensorReq struct {
	CourseId     int    `json:"courseId"`
	TeacherId    int    `json:"teacherId"`
	CensorStatus bool   `json:"censorStatus"`
	Message      string `json:"message"`
}

type AddCensorRes struct {
	Code int `json:"code"`
}
