// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.19.4
// source: courseRpc.proto

package Rpc

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CourseAddReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	CourseName string `protobuf:"bytes,1,opt,name=courseName,proto3" json:"courseName,omitempty"`
	TeacherId  int32  `protobuf:"varint,2,opt,name=teacherId,proto3" json:"teacherId,omitempty"`
	ImgUrl     string `protobuf:"bytes,3,opt,name=imgUrl,proto3" json:"imgUrl,omitempty"`
	CourseType string `protobuf:"bytes,4,opt,name=courseType,proto3" json:"courseType,omitempty"`
}

func (x *CourseAddReq) Reset() {
	*x = CourseAddReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_courseRpc_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CourseAddReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CourseAddReq) ProtoMessage() {}

func (x *CourseAddReq) ProtoReflect() protoreflect.Message {
	mi := &file_courseRpc_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CourseAddReq.ProtoReflect.Descriptor instead.
func (*CourseAddReq) Descriptor() ([]byte, []int) {
	return file_courseRpc_proto_rawDescGZIP(), []int{0}
}

func (x *CourseAddReq) GetCourseName() string {
	if x != nil {
		return x.CourseName
	}
	return ""
}

func (x *CourseAddReq) GetTeacherId() int32 {
	if x != nil {
		return x.TeacherId
	}
	return 0
}

func (x *CourseAddReq) GetImgUrl() string {
	if x != nil {
		return x.ImgUrl
	}
	return ""
}

func (x *CourseAddReq) GetCourseType() string {
	if x != nil {
		return x.CourseType
	}
	return ""
}

type UpdateCourseReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	CourseId   int32  `protobuf:"varint,1,opt,name=courseId,proto3" json:"courseId,omitempty"`
	CourseName string `protobuf:"bytes,2,opt,name=courseName,proto3" json:"courseName,omitempty"`
	ImgUrl     string `protobuf:"bytes,3,opt,name=imgUrl,proto3" json:"imgUrl,omitempty"`
	CourseType string `protobuf:"bytes,4,opt,name=courseType,proto3" json:"courseType,omitempty"`
}

func (x *UpdateCourseReq) Reset() {
	*x = UpdateCourseReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_courseRpc_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdateCourseReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateCourseReq) ProtoMessage() {}

func (x *UpdateCourseReq) ProtoReflect() protoreflect.Message {
	mi := &file_courseRpc_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateCourseReq.ProtoReflect.Descriptor instead.
func (*UpdateCourseReq) Descriptor() ([]byte, []int) {
	return file_courseRpc_proto_rawDescGZIP(), []int{1}
}

func (x *UpdateCourseReq) GetCourseId() int32 {
	if x != nil {
		return x.CourseId
	}
	return 0
}

func (x *UpdateCourseReq) GetCourseName() string {
	if x != nil {
		return x.CourseName
	}
	return ""
}

func (x *UpdateCourseReq) GetImgUrl() string {
	if x != nil {
		return x.ImgUrl
	}
	return ""
}

func (x *UpdateCourseReq) GetCourseType() string {
	if x != nil {
		return x.CourseType
	}
	return ""
}

type CourseResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Msg  string `protobuf:"bytes,1,opt,name=msg,proto3" json:"msg,omitempty"`
	Code int32  `protobuf:"varint,2,opt,name=code,proto3" json:"code,omitempty"`
	Res  bool   `protobuf:"varint,3,opt,name=res,proto3" json:"res,omitempty"`
}

func (x *CourseResp) Reset() {
	*x = CourseResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_courseRpc_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CourseResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CourseResp) ProtoMessage() {}

func (x *CourseResp) ProtoReflect() protoreflect.Message {
	mi := &file_courseRpc_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CourseResp.ProtoReflect.Descriptor instead.
func (*CourseResp) Descriptor() ([]byte, []int) {
	return file_courseRpc_proto_rawDescGZIP(), []int{2}
}

func (x *CourseResp) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

func (x *CourseResp) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *CourseResp) GetRes() bool {
	if x != nil {
		return x.Res
	}
	return false
}

type DeleteCourseReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	CourseId int32 `protobuf:"varint,1,opt,name=courseId,proto3" json:"courseId,omitempty"`
}

func (x *DeleteCourseReq) Reset() {
	*x = DeleteCourseReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_courseRpc_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteCourseReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteCourseReq) ProtoMessage() {}

func (x *DeleteCourseReq) ProtoReflect() protoreflect.Message {
	mi := &file_courseRpc_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteCourseReq.ProtoReflect.Descriptor instead.
func (*DeleteCourseReq) Descriptor() ([]byte, []int) {
	return file_courseRpc_proto_rawDescGZIP(), []int{3}
}

func (x *DeleteCourseReq) GetCourseId() int32 {
	if x != nil {
		return x.CourseId
	}
	return 0
}

type DeleteCourseResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Msg  string `protobuf:"bytes,1,opt,name=msg,proto3" json:"msg,omitempty"`
	Code int32  `protobuf:"varint,2,opt,name=code,proto3" json:"code,omitempty"`
	Res  bool   `protobuf:"varint,3,opt,name=res,proto3" json:"res,omitempty"`
}

func (x *DeleteCourseResp) Reset() {
	*x = DeleteCourseResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_courseRpc_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteCourseResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteCourseResp) ProtoMessage() {}

func (x *DeleteCourseResp) ProtoReflect() protoreflect.Message {
	mi := &file_courseRpc_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteCourseResp.ProtoReflect.Descriptor instead.
func (*DeleteCourseResp) Descriptor() ([]byte, []int) {
	return file_courseRpc_proto_rawDescGZIP(), []int{4}
}

func (x *DeleteCourseResp) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

func (x *DeleteCourseResp) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *DeleteCourseResp) GetRes() bool {
	if x != nil {
		return x.Res
	}
	return false
}

type CourseHitsReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	CourseId int32 `protobuf:"varint,1,opt,name=courseId,proto3" json:"courseId,omitempty"`
}

func (x *CourseHitsReq) Reset() {
	*x = CourseHitsReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_courseRpc_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CourseHitsReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CourseHitsReq) ProtoMessage() {}

func (x *CourseHitsReq) ProtoReflect() protoreflect.Message {
	mi := &file_courseRpc_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CourseHitsReq.ProtoReflect.Descriptor instead.
func (*CourseHitsReq) Descriptor() ([]byte, []int) {
	return file_courseRpc_proto_rawDescGZIP(), []int{5}
}

func (x *CourseHitsReq) GetCourseId() int32 {
	if x != nil {
		return x.CourseId
	}
	return 0
}

var File_courseRpc_proto protoreflect.FileDescriptor

var file_courseRpc_proto_rawDesc = []byte{
	0x0a, 0x0f, 0x63, 0x6f, 0x75, 0x72, 0x73, 0x65, 0x52, 0x70, 0x63, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x12, 0x03, 0x52, 0x70, 0x63, 0x22, 0x84, 0x01, 0x0a, 0x0c, 0x43, 0x6f, 0x75, 0x72, 0x73,
	0x65, 0x41, 0x64, 0x64, 0x52, 0x65, 0x71, 0x12, 0x1e, 0x0a, 0x0a, 0x63, 0x6f, 0x75, 0x72, 0x73,
	0x65, 0x4e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x63, 0x6f, 0x75,
	0x72, 0x73, 0x65, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x1c, 0x0a, 0x09, 0x74, 0x65, 0x61, 0x63, 0x68,
	0x65, 0x72, 0x49, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x09, 0x74, 0x65, 0x61, 0x63,
	0x68, 0x65, 0x72, 0x49, 0x64, 0x12, 0x16, 0x0a, 0x06, 0x69, 0x6d, 0x67, 0x55, 0x72, 0x6c, 0x18,
	0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x69, 0x6d, 0x67, 0x55, 0x72, 0x6c, 0x12, 0x1e, 0x0a,
	0x0a, 0x63, 0x6f, 0x75, 0x72, 0x73, 0x65, 0x54, 0x79, 0x70, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x0a, 0x63, 0x6f, 0x75, 0x72, 0x73, 0x65, 0x54, 0x79, 0x70, 0x65, 0x22, 0x85, 0x01,
	0x0a, 0x0f, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x43, 0x6f, 0x75, 0x72, 0x73, 0x65, 0x52, 0x65,
	0x71, 0x12, 0x1a, 0x0a, 0x08, 0x63, 0x6f, 0x75, 0x72, 0x73, 0x65, 0x49, 0x64, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x05, 0x52, 0x08, 0x63, 0x6f, 0x75, 0x72, 0x73, 0x65, 0x49, 0x64, 0x12, 0x1e, 0x0a,
	0x0a, 0x63, 0x6f, 0x75, 0x72, 0x73, 0x65, 0x4e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x0a, 0x63, 0x6f, 0x75, 0x72, 0x73, 0x65, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x16, 0x0a,
	0x06, 0x69, 0x6d, 0x67, 0x55, 0x72, 0x6c, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x69,
	0x6d, 0x67, 0x55, 0x72, 0x6c, 0x12, 0x1e, 0x0a, 0x0a, 0x63, 0x6f, 0x75, 0x72, 0x73, 0x65, 0x54,
	0x79, 0x70, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x63, 0x6f, 0x75, 0x72, 0x73,
	0x65, 0x54, 0x79, 0x70, 0x65, 0x22, 0x44, 0x0a, 0x0a, 0x43, 0x6f, 0x75, 0x72, 0x73, 0x65, 0x52,
	0x65, 0x73, 0x70, 0x12, 0x10, 0x0a, 0x03, 0x6d, 0x73, 0x67, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x03, 0x6d, 0x73, 0x67, 0x12, 0x12, 0x0a, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x05, 0x52, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x12, 0x10, 0x0a, 0x03, 0x72, 0x65, 0x73,
	0x18, 0x03, 0x20, 0x01, 0x28, 0x08, 0x52, 0x03, 0x72, 0x65, 0x73, 0x22, 0x2d, 0x0a, 0x0f, 0x44,
	0x65, 0x6c, 0x65, 0x74, 0x65, 0x43, 0x6f, 0x75, 0x72, 0x73, 0x65, 0x52, 0x65, 0x71, 0x12, 0x1a,
	0x0a, 0x08, 0x63, 0x6f, 0x75, 0x72, 0x73, 0x65, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05,
	0x52, 0x08, 0x63, 0x6f, 0x75, 0x72, 0x73, 0x65, 0x49, 0x64, 0x22, 0x4a, 0x0a, 0x10, 0x44, 0x65,
	0x6c, 0x65, 0x74, 0x65, 0x43, 0x6f, 0x75, 0x72, 0x73, 0x65, 0x52, 0x65, 0x73, 0x70, 0x12, 0x10,
	0x0a, 0x03, 0x6d, 0x73, 0x67, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6d, 0x73, 0x67,
	0x12, 0x12, 0x0a, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x04,
	0x63, 0x6f, 0x64, 0x65, 0x12, 0x10, 0x0a, 0x03, 0x72, 0x65, 0x73, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x08, 0x52, 0x03, 0x72, 0x65, 0x73, 0x22, 0x2b, 0x0a, 0x0d, 0x43, 0x6f, 0x75, 0x72, 0x73, 0x65,
	0x48, 0x69, 0x74, 0x73, 0x52, 0x65, 0x71, 0x12, 0x1a, 0x0a, 0x08, 0x63, 0x6f, 0x75, 0x72, 0x73,
	0x65, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x08, 0x63, 0x6f, 0x75, 0x72, 0x73,
	0x65, 0x49, 0x64, 0x32, 0xe3, 0x01, 0x0a, 0x09, 0x63, 0x6f, 0x75, 0x72, 0x73, 0x65, 0x52, 0x70,
	0x63, 0x12, 0x2f, 0x0a, 0x09, 0x41, 0x64, 0x64, 0x43, 0x6f, 0x75, 0x72, 0x73, 0x65, 0x12, 0x11,
	0x2e, 0x52, 0x70, 0x63, 0x2e, 0x43, 0x6f, 0x75, 0x72, 0x73, 0x65, 0x41, 0x64, 0x64, 0x52, 0x65,
	0x71, 0x1a, 0x0f, 0x2e, 0x52, 0x70, 0x63, 0x2e, 0x43, 0x6f, 0x75, 0x72, 0x73, 0x65, 0x52, 0x65,
	0x73, 0x70, 0x12, 0x3b, 0x0a, 0x0c, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x43, 0x6f, 0x75, 0x72,
	0x73, 0x65, 0x12, 0x14, 0x2e, 0x52, 0x70, 0x63, 0x2e, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x43,
	0x6f, 0x75, 0x72, 0x73, 0x65, 0x52, 0x65, 0x71, 0x1a, 0x15, 0x2e, 0x52, 0x70, 0x63, 0x2e, 0x44,
	0x65, 0x6c, 0x65, 0x74, 0x65, 0x43, 0x6f, 0x75, 0x72, 0x73, 0x65, 0x52, 0x65, 0x73, 0x70, 0x12,
	0x35, 0x0a, 0x0c, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x43, 0x6f, 0x75, 0x72, 0x73, 0x65, 0x12,
	0x14, 0x2e, 0x52, 0x70, 0x63, 0x2e, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x43, 0x6f, 0x75, 0x72,
	0x73, 0x65, 0x52, 0x65, 0x71, 0x1a, 0x0f, 0x2e, 0x52, 0x70, 0x63, 0x2e, 0x43, 0x6f, 0x75, 0x72,
	0x73, 0x65, 0x52, 0x65, 0x73, 0x70, 0x12, 0x31, 0x0a, 0x0a, 0x43, 0x6f, 0x75, 0x72, 0x73, 0x65,
	0x48, 0x69, 0x74, 0x73, 0x12, 0x12, 0x2e, 0x52, 0x70, 0x63, 0x2e, 0x43, 0x6f, 0x75, 0x72, 0x73,
	0x65, 0x48, 0x69, 0x74, 0x73, 0x52, 0x65, 0x71, 0x1a, 0x0f, 0x2e, 0x52, 0x70, 0x63, 0x2e, 0x43,
	0x6f, 0x75, 0x72, 0x73, 0x65, 0x52, 0x65, 0x73, 0x70, 0x42, 0x07, 0x5a, 0x05, 0x2e, 0x2f, 0x52,
	0x70, 0x63, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_courseRpc_proto_rawDescOnce sync.Once
	file_courseRpc_proto_rawDescData = file_courseRpc_proto_rawDesc
)

func file_courseRpc_proto_rawDescGZIP() []byte {
	file_courseRpc_proto_rawDescOnce.Do(func() {
		file_courseRpc_proto_rawDescData = protoimpl.X.CompressGZIP(file_courseRpc_proto_rawDescData)
	})
	return file_courseRpc_proto_rawDescData
}

var file_courseRpc_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_courseRpc_proto_goTypes = []interface{}{
	(*CourseAddReq)(nil),     // 0: Rpc.CourseAddReq
	(*UpdateCourseReq)(nil),  // 1: Rpc.UpdateCourseReq
	(*CourseResp)(nil),       // 2: Rpc.CourseResp
	(*DeleteCourseReq)(nil),  // 3: Rpc.DeleteCourseReq
	(*DeleteCourseResp)(nil), // 4: Rpc.DeleteCourseResp
	(*CourseHitsReq)(nil),    // 5: Rpc.CourseHitsReq
}
var file_courseRpc_proto_depIdxs = []int32{
	0, // 0: Rpc.courseRpc.AddCourse:input_type -> Rpc.CourseAddReq
	3, // 1: Rpc.courseRpc.DeleteCourse:input_type -> Rpc.DeleteCourseReq
	1, // 2: Rpc.courseRpc.UpdateCourse:input_type -> Rpc.UpdateCourseReq
	5, // 3: Rpc.courseRpc.CourseHits:input_type -> Rpc.CourseHitsReq
	2, // 4: Rpc.courseRpc.AddCourse:output_type -> Rpc.CourseResp
	4, // 5: Rpc.courseRpc.DeleteCourse:output_type -> Rpc.DeleteCourseResp
	2, // 6: Rpc.courseRpc.UpdateCourse:output_type -> Rpc.CourseResp
	2, // 7: Rpc.courseRpc.CourseHits:output_type -> Rpc.CourseResp
	4, // [4:8] is the sub-list for method output_type
	0, // [0:4] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_courseRpc_proto_init() }
func file_courseRpc_proto_init() {
	if File_courseRpc_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_courseRpc_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CourseAddReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_courseRpc_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UpdateCourseReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_courseRpc_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CourseResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_courseRpc_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeleteCourseReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_courseRpc_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeleteCourseResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_courseRpc_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CourseHitsReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_courseRpc_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_courseRpc_proto_goTypes,
		DependencyIndexes: file_courseRpc_proto_depIdxs,
		MessageInfos:      file_courseRpc_proto_msgTypes,
	}.Build()
	File_courseRpc_proto = out.File
	file_courseRpc_proto_rawDesc = nil
	file_courseRpc_proto_goTypes = nil
	file_courseRpc_proto_depIdxs = nil
}
