// Code generated by goctl. DO NOT EDIT!
// Source: studentrpc.proto

package server

import (
	"context"

	"onlineEudcation/Student/rpc/internal/logic"
	"onlineEudcation/Student/rpc/internal/svc"
	"onlineEudcation/Student/rpc/rpc"
)

type StudentRpcServer struct {
	svcCtx *svc.ServiceContext
	rpc.UnimplementedStudentRpcServer
}

func NewStudentRpcServer(svcCtx *svc.ServiceContext) *StudentRpcServer {
	return &StudentRpcServer{
		svcCtx: svcCtx,
	}
}

func (s *StudentRpcServer) AddStudent(ctx context.Context, in *rpc.StudentAddReq) (*rpc.StudentAddRes, error) {
	l := logic.NewAddStudentLogic(ctx, s.svcCtx)
	return l.AddStudent(in)
}
