// Code generated by goctl. DO NOT EDIT.
package handler

import (
	"net/http"

	"onlineEudcation/Vedio/api/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPost,
				Path:    "/findCourseVideos",
				Handler: findCourseVideosHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/addVideo",
				Handler: addVideoHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/deleteVideo",
				Handler: deleteVideoHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/updateVideo",
				Handler: updateVideoHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/findVideoById",
				Handler: findVideoByIdHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/videoHits",
				Handler: videoHitsHandler(serverCtx),
			},
		},
		rest.WithPrefix("/video"),
	)
}
