// Code generated by goctl. DO NOT EDIT.
package types

type TeacherInfoForRegister struct {
	Username string `json:"username"`
	Password string `json:"password"`
	Email    string `json:"email"`
}

type UserInfo struct {
	TeacherRes  TeacherResponse        `json:"teacherRes"`
	Id          int32                  `json:"id"`
	TeacherInfo TeacherInfoForRegister `json:"teacherinfo"`
}

type TeacherResponse struct {
	Code    int32  `json:"code"`
	Res     bool   `json:"res"`
	Message string `json:"message"`
}

type TeacherInfoForLogin struct {
	Email    string `json:"email"`
	Password string `json:"password"`
}
